### PR TITLE
Alias rule controller

### LINKED ISSUE #25: Action aliases in the controller
Here's another idea:

In my application I authorise a lot of controllers based on a simple (user editable) permissions system, so the policy structure is quite simple and has nothing to do with these controller items and more to do with their ultimate position within a tree structure and the permissions applied there. To that end I'm calling something like `authorise! ComponentInstance` to kick off the policy check.

Now that's all fine and good and I can define rule aliases in the policy for common actions:

```
  authorize :component_instance

  alias_rule :index?, :show?, to: :view?
  alias_rule :new?, :create?, :update?, :destroy?, to: :edit?

  def view?
    component_instance.has_permission_to(:view, user)
  end

  def edit?
    component_instance.has_permission_to(:edit, user)
  end
```

However, in some of my controllers there are other actions (e.g. `sort`) and some that are injected by concerns. In that case, it's illogical to keep adding those rule aliases to the policy, it'd be better to pass in the alias from the controller and I can see one can do that:

`authorize! ComponentInstance, to: :view?`

I was wondering what you thought of creating a method for defining rule aliases at the controller level, so I could do something like:

`alias_action :sort, :jumble, to_rule: :edit?`

So when you're identifying the rule to execute you could check this first, then move down to the rule aliases in the policy?

### PR DESCRIPTION
**Pull request by brendon**
Closes #25 

### What is the purpose of this pull request?
Allows one to alias rules in the controller. These aliases are inspected before then passing the resolved rule on to the policy so it's then theoretically possible to have further aliases in the policy.

### What changes did you make? (overview)
Modified the Rails controller concern with methods for `action_aliases`

### Is there anything you'd like reviewers to focus on?
I haven't done any tests yet but I've tested this in my application and it works well. This is more of a 'what do you think?' attempt. Let me know if you have any suggestions.

PR checklist:

- [ ] Tests included
- [ ] Documentation updated
- [ ] Changelog entry added

### CODE REVIEW

**Comment by brendon** [comment]
I've inadvertently added in my fixes from #22 but I guess they're required to make this work as expected. We can strip them out if need be.

**Comment by palkan** [comment]
To be honest, I'm against of adding a too Rails-specific functionality.

Also, let's wait for `implicit_authorized_record` API (https://github.com/palkan/action_policy/issues/17#issuecomment-398693964); that could solve the problem in a different way.

**Comment by brendon** [comment]
Hi @palkan, I'm happy to look at solving this another way, but I don't see anything in `implicit_authorized_record` that allows me to add policy aliases from the controller end. Could you point me in the right direction regarding what you have in mind?

Just to re-iterate, my major use for this would be in Controller Concerns that are mixed into various controllers to provide extra actions. Having the Concern able to define its own aliases would keep things nicely encapsulated.

**Comment by palkan** [comment]
Closed as stale

**Comment by brendon** [comment]
Hi @palkan, I was waiting on a response from you on this one. I honestly can't remember much about this anymore but it looks like I'm still using my fork of the code in my app. Did https://github.com/palkan/action_policy/issues/17 end up adding functionality similar to this?

**Comment by brendon** [comment]
Ah I see, it was related to this: #25 

I still think this would be a useful feature. Seems no one else thinks so :D

**Pull request closed without merging**
