### PR TITLE
Allow using callable objects as scopes #261

### PR DESCRIPTION
**Pull request by killondark**
Hi @palkan. Please check my PR by issue #261

### CODE REVIEW

**Comment by killondark** [comment]
@palkan, up.

**Review by palkan — CHANGES_REQUESTED** [review]
Thanks!

But no tests—how so?

**Comment by killondark** [comment]
Hi @palkan. I wrote tests, fixed logic and updated documentation.

**Review by palkan — APPROVED** [review]
Thanks!

**Pull request merged**
